export const API = "/api";
export const paths = {
  projects: `${API}/projects`,
  project: (id: string) => `${API}/projects/${id}`,
  scan: (id: string) => `${API}/projects/${id}/scan`,
  branches: (id: string) => `${API}/projects/${id}/branches`,
  specs: `${API}/specs`,
  spec: (id: string) => `${API}/specs/${id}`,
  triggers: `${API}/triggers`,
  trigger: (id: string) => `${API}/triggers/${id}`,
  toggle: (id: string) => `${API}/triggers/${id}/toggle`,
  settings: `${API}/settings`,
  runs: `${API}/runs`,
  run: (id: string) => `${API}/runs/${id}`,
  runLog: (id: string) => `${API}/runs/${id}/log`,
  runCommand: (id: string) => `${API}/runs/${id}/command`,
  runControl: (id: string) => `${API}/runs/${id}/control`,
  runSteer: (id: string) => `${API}/runs/${id}/steer`,
  docs: (id: string) => `${API}/projects/${id}/docs`,
  docFile: (id: string, path: string) => `${API}/projects/${id}/docs/${path}`,
  fsBrowse: (path?: string) => `${API}/fs/browse${path ? `?path=${encodeURIComponent(path)}` : ""}`,
  terminalSessions: `${API}/terminal/sessions`,
  terminalSession: (id: string) => `${API}/terminal/sessions/${id}`,
  terminalWs: (id: string) => `${API}/terminal/sessions/${id}/ws`,
} as const;
