export const API = "/api";
export const paths = {
  projects: `${API}/projects`,
  project: (id: string) => `${API}/projects/${id}`,
  branches: (id: string) => `${API}/projects/${id}/branches`,
  specs: `${API}/specs`,
  spec: (id: string) => `${API}/specs/${id}`,
  specDocs: (id: string) => `${API}/specs/${id}/docs`,
  specDocFile: (id: string, path: string) => `${API}/specs/${id}/docs/${path}`,
  specIntegrate: (id: string) => `${API}/specs/${id}/integrate`,
  specReview: (id: string) => `${API}/specs/${id}/review`,
  specReviewFile: (id: string, path: string) => `${API}/specs/${id}/review/${path}`,
  settings: `${API}/settings`,
  notifications: `${API}/notifications`,
  limits: `${API}/limits`,
  docs: (id: string) => `${API}/projects/${id}/docs`,
  docFile: (id: string, path: string) => `${API}/projects/${id}/docs/${path}`,
  // SPEC-182 · IDE Visual
  ideTree: (id: string, ref = "") => `${API}/projects/${id}/tree${ref ? `?ref=${encodeURIComponent(ref)}` : ""}`,
  ideFile: (id: string, path?: string, ref = "") =>
    `${API}/projects/${id}/file${path ? `?path=${encodeURIComponent(path)}${ref ? `&ref=${encodeURIComponent(ref)}` : ""}` : ""}`,
  ideGraph: (id: string, limit = 200) => `${API}/projects/${id}/graph?limit=${limit}`,
  ideCommit: (id: string, sha: string) => `${API}/projects/${id}/commit/${sha}`,
  ideGit: (id: string) => `${API}/projects/${id}/git`,
  fsBrowse: (path?: string) => `${API}/fs/browse${path ? `?path=${encodeURIComponent(path)}` : ""}`,
  terminalSessions: `${API}/terminal/sessions`,
  terminalSession: (id: string) => `${API}/terminal/sessions/${id}`,
  terminalPhases: (id: string) => `${API}/terminal/sessions/${id}/phases`,
  terminalWs: (id: string) => `${API}/terminal/sessions/${id}/ws`,
  eventsWs: `${API}/events/ws`,   // SPEC-199 · WebSocket siar dashboard (global, bukan per-sesi)
  vps: `${API}/vps`,
  vpsOne: (id: string) => `${API}/vps/${id}`,
  vpsAudit: (id: string) => `${API}/vps/${id}/audit`,
  vpsHarden: (id: string) => `${API}/vps/${id}/harden`,
  vpsSession: (id: string) => `${API}/vps/${id}/session`,
  // SPEC-169 · auth
  authStatus: `${API}/auth/status`,
  authSetup: `${API}/auth/setup`,
  authLogin: `${API}/auth/login`,
  authLogout: `${API}/auth/logout`,
  authUsers: `${API}/auth/users`,
  authUser: (id: string) => `${API}/auth/users/${id}`,
  authChangePassword: `${API}/auth/change-password`,
} as const;
