import { z } from "zod";
export const zStage = z.enum(["brainstorming","objective","spec-ready","planned","executing","done"]);
export const zSpecSource = z.enum(["brief","qa"]);
export const zRunStatus = z.enum(["queued","running","paused","stopped","failed","done"]);
export const zRunKind = z.enum(["feature","qa","scaffold"]);
export const zTriggerType = z.enum(["commit","schedule","manual","interval"]);
export const zTriggerTarget = z.enum(["plan + execute","audit","qa audit","scaffold docs"]);
export const zDocStatus = z.enum(["ok","drift","broken"]);
export const zPriority = z.enum(["tinggi","sedang","rendah"]);
export const zProjectKind = z.enum(["from-scratch","existing"]);
export const zSeverity = z.enum(["critical","major","minor"]);
